### ISSUE TITLE
Предложение @rus-ai по изменению логики удаления пользователя и/или сообщения

### ISSUE THREAD

**Issue by stepanskryabin** [MoreliaTalk/morelia_protocol#14]
@rus-ai 
> Мне кажется если полное удаление юзера и можно оправдать то полное удаление сообщения это неправильно.
> После удаления сообщения с персональными данными например или с оскорблениями важно чтобы информация об
> удалении ушла на все клиенты. Чтобы они убрали его из чата.
> Но не все клиенты в данный момент на связи синхронно рассылать информацию об удалении нельзя, а то те кто
> переподключись через минуту сообщения не удалят. При удалении сообщений точно нужно завести флаг is_deleted
>
> Заодно предлагаю не удалять юзера целиком пока а заменять ему логин и пароль случайными числами, а юзернейм
> менять на "Deleted user". Остальные поля типа емэйл, био и аватарку зачищать.

**Comment by stepanskryabin** [comment]
Считаю функция полного удаления информации пользователя о себе и о своих сообщениях должна работать так как она и называется, без всяких дополнительных флагов. Удаление должно быть полным, и не восстановимым.

По поводу обновления удалённого сообщения на других клиентах, видимо необходимо продумать этот момент отдельно и внести правки в метод get_update. Например разделить get_update на несколько методов, которые будет запрашивать обновления потоков, юзеров, сообщений по отдельности. Или добавить в метод get_update специальный объект в котором отправлять id всех сообщений и потоков которые были удалены.

**Comment by stepanskryabin** [comment]
> 
> 
> Считаю функция полного удаления информации пользователя о себе и о своих сообщениях должна работать так как она и называется, без всяких дополнительных флагов. Удаление должно быть полным, и не восстановимым.
> 
> По поводу обновления удалённого сообщения на других клиентах, видимо необходимо продумать этот момент отдельно и внести правки в метод get_update. Например разделить get_update на несколько методов, которые будет запрашивать обновления потоков, юзеров, сообщений по отдельности. Или добавить в метод get_update специальный объект в котором отправлять id всех сообщений и потоков которые были удалены.

Дополню: для удаления сообщения никакого дополнительного флага не нужно, нужно просто изменить реализованный метод delete_message путём не удаления сообщения, а изменения текста сообщения текстом "Сообщение удалено пользователем", с возвратом результата выполнения этого метода. Например:
Пример запроса:
```
{
    "type": "delete_message",
    "data": {
        "message": [{
            "id": 858585,
            "text": "User delete this message"
            }],
        "user": [{
            "uuid": 5345634567354,
            "auth_id": "lkds89ds89fd98fd"
            }],
        "meta": null
        },
    "jsonapi": {
        "version": "1.0"
        },
    "meta": null
    }
```

Пример ответа (успех):
```
{
    "type": "delete_message",
    "data": null,
    "errors": {
        "code": 200,
        "status": "OK",
        "time": 1594492370,
        "detail": "successfully"
        },
    "jsonapi": {
        "version": "1.0"
        },
    "meta": null
    }
```

**Comment by rus-ai** [comment]
Юзера тоже так надо как сообщение - зачищать все поля кроме uuid включая auth_id чтобы сразу разлогинился. И установить невозможный хэш пароля. А вместо Username "Deleted user". 

А если этого не сделать то сообщения останутся сиротами и будут ссылаться на несуществующий uuid.

Более того если новому юзеру случайно выдадут тот же uuid то он присвоит все сообщения себе.

**Comment by stepanskryabin** [comment]
> 
> 
> Юзера тоже так надо как сообщение - зачищать все поля кроме uuid включая auth_id чтобы сразу разлогинился. И установить невозможный хэш пароля. А вместо Username "Deleted user".
> 
> А если этого не сделать то сообщения останутся сиротами и будут ссылаться на несуществующий uuid.
> 
> Более того если новому юзеру случайно выдадут тот же uuid то он присвоит все сообщения себе.

Дельно. Так и реалищую.

**Comment by stepanskryabin** [comment]
Выполнено.
