### ISSUE TITLE
Необходимый функционал который надо добавить в ревизию 1.15

### ISSUE THREAD

**Issue by stepanskryabin** [MoreliaTalk/morelia_protocol#16]
Добавить:
1. метод add_flow
2. метод all_flow
3. имя для протокола Mårran (Морра)

Изменить:
1. в выдаваемом результате работы метода add_flow размещать информацию о новом flow (flowId, timeCreated, flowType, title, info)

**Comment by stepanskryabin** [comment]
Исправить методы регистрации и авторизации. В запросе register_user должен приходить пароль, логин, ключ, соль, в ответе будет хэш пароля и UUID. В запросе authentification должен приходить uuid и хэш пароля, в ответе будет токен аутентификации auth_id.

**Comment by stepanskryabin** [comment]
Добавить Код ошибки 409 "Conflict" - конфликт. Для случаев регистрации юзера с логином который уже есть в БД и используется другим юзером.

**Comment by NekrodNIK** [comment]
В общем придумал взаимодействие сервера и клиента: 
1)Клиент регистрируется или входит(делается один раз на новом устройстве или если на этом устройстве вышли) 
2)При каждом заходе в клиент он аутенфицируется(проверяется его валидность) 
3)При выборе определённого Flow клиент смотрит в свою бд и если там нет сообщений от него то он посылает запрос всех сообщений этого flow, иначе он запрашивает все сообщения по Id больших чем последнее полученное(да не по времени, по id точнее и проще) 
4)Клиент ждёт сообщений от этого flow и сам их отправляет

**Comment by NekrodNIK** [comment]
> 3\. имя для протокола Mårran (Морра)

Надо ещё подумать на именем

**Comment by stepanskryabin** [comment]
> 
> 
> > 3. имя для протокола Mårran (Морра)
> 
> Надо ещё подумать на именем

я уже назвал его Udav. Морра слишком гнетуще.

**Comment by stepanskryabin** [comment]
> 
> 
> В общем придумал взаимодействие сервера и клиента:
> 1)Клиент регистрируется или входит(делается один раз на новом устройстве или если на этом устройстве вышли)
> 2)При каждом заходе в клиент он аутенфицируется(проверяется его валидность)
> 3)При выборе определённого Flow клиент смотрит в свою бд и если там нет сообщений от него то он посылает запрос всех сообщений этого flow, иначе он запрашивает все сообщения по Id больших чем последнее полученное(да не по времени, по id точнее и проще)
> 4)Клиент ждёт сообщений от этого flow и сам их отправляет

1 и 2 пункты принимаются.

3 и 4 по ID сообщения не запросить, т.к. ID'шники присваиваются вразнабой.

**Comment by stepanskryabin** [comment]
> 
> 
> Исправить методы регистрации и авторизации. В запросе register_user должен приходить пароль, логин, ключ, соль, в ответе будет хэш пароля и UUID. В запросе authentification должен приходить uuid и хэш пароля, в ответе будет токен аутентификации auth_id.

Изменил чуть-чуть логику:
регистрация - в запросе password, salt, key, login. в ответе uuid.
авторизация - в запросе login, password. в ответе uuid, auth_id
