### ISSUE TITLE
Не соответствует описание

### ISSUE THREAD

**Issue by Hazzari** [MoreliaTalk/morelia_protocol#21]
В описании есть строка:
"Приложения общаются между собой путём отправки JSON-файла."

Сейчас сервер общается путем отправки в формате sting

**Comment by stepanskryabin** [comment]
> 
> 
> В описании есть строка:
> "Приложения общаются между собой путём отправки JSON-файла."
> 
> Сейчас сервер общается путем отправки в формате sting

а как лучше? JSON-объект?

**Comment by Hazzari** [comment]
Лучше - так что бы описание соответствовало действительности, как общаются, чтоб так и было описано

**Comment by stepanskryabin** [comment]
Выполнено.
