### ISSUE TITLE
Метод user_info

### ISSUE THREAD

**Issue by rus-ai** [MoreliaTalk/morelia_protocol#22]
На текущий момент описание метода:

_Метод позволяет клиенту получить от сервера информацию о своих настройках._

Предлагаю два изменения:
**Позволить запрашивать информацию о других пользователях**

В любом случае необходимо после обработки all_messages получить по uuid пользователей их имена, и делать это может только авторизованный пользователь. Я считаю что расширение функционала данного метода, вместо создания нового метода будет способствовать неусложнению протокола и в то же время не внесет путаницы. 

При этом первый объект User в протоколе всегда сам делающий запрос пользователь, это нужно для проверки авторизации, следующие объекты Users запрашиваемые другие пользователи.

**Позволить запрашивать несколько пользователей за один раз** 

Если первое улучшение протокола удастся реализовать то неплохо бы сделать возможность запроса любого количества пользователей. Дело в том что после загрузки списка сообщений через all_messages клиент будет вынужден сделать запрос имени для каждого неизвестного пользователя. Лучше объединить несколько запросов в один для снижения нагрузки на протокол.

**Дополнительно идеи**

По максимальному числу пользователей запрошенных за раз возможно стоит внести ограничение на сервере. Вынести параметр в config сервера. Но не менее 2 (себя и минимум дополнительно одного). Если запрошено больше чем задано в параметре сервер (клиент может не знать настройки конкретного сервера) должен не выдавать ошибку, а вернуть данные по первым N объектам, где N это и есть параметр.
Можно так же внести ограничение не в параметр сервера а в протокол, тогда при запросе больше чем разрешено по протоколу сервер должен возвращать ошибку.

**Итого**

Новое описание метода:

_Метод позволяет клиенту получить от сервера информацию о своих настройках, так же общедоступную информацию о других пользователях по их uuid_

Пример запроса:

```
{
    "type": "user_info",
    "data": {
        "user": [{
            "uuid": 111111111,
            "auth_id": "dks7sd9f6g4fg67vb78g65"
            }, {
            "uuid": 222222222
            }, {
            "uuid": 333333333
            }],
        "meta": null
        },
    "jsonapi": {
        "version": "1.0"
        },
    "meta": null
    }
}
```

Пример ответа:

```
{
    "type": "user_info",
    "data": {
        "user": [{
            "uuid": 111111111,
            "login": "username1",
            "password": "lksdjflksjfsd",
            "salt": "salt",
            "key": "key"
            "username": "Vasya",
            "is_bot": true,
            "auth_id": "dfhdfghdfghdfgh",
            "email": "querty@querty.com",
            "avatar": "fffdddddd",
            "bio": "My bio"
            },{
            "uuid": 2222222222,
            "username": "Tony",
            "is_bot": true,
            "avatar": "fffdddddd",
            "bio": "My bio"
            },{
            "uuid": 3333333333,
            "username": "Marta",
            "is_bot": false,
            "avatar": "fffdddddd",
            "bio": "My bio"
            }],
        "meta": null
        },
    "errors": {
        "code": 200,
        "status": "OK",
        "time": 1594492370,
        "detail": "successfully"
        },
    "jsonapi": {
        "version": "1.0"
        },
    "meta": null
    }
}
```

**Comment by stepanskryabin** [comment]
Обновил описание. Теперь метод позволяет получить только общедоступную ифнормацию о любом пользователе.
