### ISSUE TITLE
Метод all_messages - пагинация

### ISSUE THREAD

**Issue by rus-ai** [MoreliaTalk/morelia_protocol#23]
**Добавить пагинацию**

Предлагаю закрепить в протоколе что сервер имеет право (но не обязан) ограничить выдачу сообщений за один запрос.

На данный момент сервер обязан вернуть все сообщения с датой/временем после заданного времени, даже если сообщений будет 1000000. Это приведет к долгой обработке запроса и большого многомегабайтного пакета данных.

**Мое предложение** 

У сервера может быть задан параметр `max_messages_response`, который должен быть не меньше 1. При отправке сообщений сервер отправляет только число сообщений не больше `max_messages_response` начиная с самых старых, но моложе чем параметр `time`. О том что выданы не все сообщения сервер не сообщает.
Клиент получив такой пакет при следующем запросе поменяет `time` на время самого свежего сообщения и сделает повторный запрос на остаточную часть. 

**Таким образом внесенные изменения в протокол не повлияют на совместимость с дествующими клиентами и серверами, но позволят избежать нагрузок в будущем.**

Новое описание:

Метод позволяет получить все сообщения в потоке `flow`, за период с начала времени `time` по настоящее время. Если число сообщений слишком велико, сервер имеет право выдать лишь часть сообщений - самых старых соотвествующих запросу, при этом в ошибках никак не уведомив клиента о том что сообщений больше чем возвращено.

**Идеи**
Пока протокол легко поменять, возможно стоит в случае если сообщений больше чем возвращено выдавать не 200 код ошибки, а ввести новый 20х код. Это позволит клиенту сделать следующий запрос мгновенно после обработки первой порции, а не выжидая таймаут. Очень подходит код из `HTTP 206 Partial Content («частичное содержимое»)`

**Comment by stepanskryabin** [comment]
Выполнено.
