### ISSUE TITLE
Метод send_message

### ISSUE THREAD

**Issue by rus-ai** [MoreliaTalk/morelia_protocol#26]
В данный момент в случае успеха возвращает message_id который присвоен сообщению на сервере. Но клиент никак не может сопоставить на какую из нескольких отправленных сообщений пришёл ответ. Соответственно не может показать статус что сообщение добавлено или предпринять повторную отправку. Нужны способы привязки. 

Вариант 1: возвращать само сообщение обратно чтобы клиент понял в какой поток и какой текст прошёл или не прошёл.

Минусы первого варианта - высокий трафик, и придется препятствовать отправке одинаковых сообщений до подтверждения первого отправленного.

Вариант 2: клиент присваивает сообщению свой временный локальный id и сервер в ответ клиенту отправляет вместе со статусом этот же "client_generated_id". Клиент будет понимать какое именно из его сообщений прошло или не прошло. Серверу хранить в базе назначенный клиентом id не нужно. Можно забыть сразу после обработки запроса.

Минусов у второго варианта не вижу.
id предлагаю сделать целым числом, не uuid это никак не влияет на безопасность. Сервер не знает логику присвоения id на клиенте (она может быть сквозной с момента подключения или просто порядковый номер сообщений в очереди на отправку или повторную отправку.

**Comment by stepanskryabin** [comment]
Реализован 2-й вариант.
