### ISSUE TITLE
Протокол шифрования

### ISSUE THREAD

**Issue by baterflyrity** [MoreliaTalk/morelia_protocol#34]
Привет! Прочитал вашу рекламу на сайте и заинтересовался питоновским мессенджером. К несчастью, в протоколе и в клиентах не указано ничего про шифрование, анонимность, безопасность и иже с ними. Я правильно понимаю, что это всего лишь триггерные слова для заманивания пользователей и ничего подобного на самом деле нет?

**Comment by rus-ai** [comment]
Привет. Я конечно больше занимаюсь клиентской частью, так что не претендую на абсолютно точный ответ, но расскажу как я вижу. 

1. Сейчас действительно в протоколе нет никакой криптографии, дело в том что задача к 1 релизу получить полноценный рабочий клиент и сервер. На этом этапе решено ограничиться p2s шифрованием tls. 
2. Но действительно в будущем планируется использование несимметричного шифрования, и протокол для этого кардинально переделывать не придётся, только расширять. 
3. Мы планируем не только аналоги защищённых чатов телеграмм, или чатов WhatsApp с p2p шифрованием, но и "защищённые группы", сообщения которых будут храниться на сервере ы защищённом виде, пару месяцев назад предварительно обсуждали в телеграмм чате разработчиков, в том числе есть ли возможность дать доступ к ранее зашифрованным сообщениям новому участнику, или участнику будет доступны только сообщения отправленные во время его членства. В том числе пришли к заключению что можно попробовать реализовать и предоставление новому частнику доступа к ранним перепискам.

**Comment by baterflyrity** [comment]
Я так полагаю, что от шифрования решили отказаться?)

**Comment by NekrodNIK** [comment]
Нет, никто от шифрования не отказывался. Однако на вопрос мы ответили, тогда зачем этот тикет далее держать открытым?

**Comment by baterflyrity** [comment]
Мне следует создать новую тему для добавления шифрования в протокол? Я говорю о добавлении технического описания шифрования в данный репозиторий, т.е. в официальную документацию, чтобы можно было программно работать с ним.

**Comment by NekrodNIK** [comment]
Вы можете прокомментировать тикет #33, т.к. в шифрование(как, собственно и много чего другого), планируется добавить именно в версии протокола 2.0
