### ISSUE TITLE
Замечания к протоколу

### ISSUE THREAD

**Issue by rus-ai** [MoreliaTalk/morelia_protocol#9]
1. Зачем нужен метод ping-pong - если websocket в любом случае обеспечивает связь с установкой соединения? Я вижу только применение - в дальнейшем реализовать дополнительно api http get/post
2. В методе send_message - есть два объекта указывающих на чат/канал. flow и from_flow. Зачем дублирование? Разве что рассматривать from_flow как пересланное сообщение. Но тогда нужен вариант from_user. 
3. Все таки нужен вариант type=general_error на случай невозможности парсинга запроса по вине сервера или клиента.
4. Является ли "register_user" одновременно "authenticate". Судя по полю auth_id - является. Но тогда не ясно его поведение а случае если пользователь с таким логином уже был зарегистрирован. При повторной регистрации аутентификацию не вернут?

**Comment by stepanskryabin** [comment]
1. Резон вот в чём: Я на днях слушал подкаст, где рассказывали про систему аналогичную нашей (пересылка по сети сообщений в виде JSON-объекта между одним сервером и множеством клиентов) и у них возникла проблема c большим количеством "миртуальных" клиентов. Виртуальных в смысле они подключились к серверу, он сохранил параметры подключения в память, а потом клиент отключался и снова переподключался. В таком случае сервер думал, что это другой клиент, и вновь сохранял в памяти параметры подключения. Для того чтобы прекратить разбазаривание памяти автор того проекта сделал подобный метод пинг-понг. Мой метод ещё нужно дорабатывать, например там нет идентификатора клиента.

**Comment by stepanskryabin** [comment]
3. Нужен обязательно. Я его реализую.

**Comment by stepanskryabin** [comment]
4. Да является. Нужно ли разделить регистрацию и аутентификацию вообще? Очень может быть! На текущем этапе считаю ненужным такое разделение, но в дальнейшем скорее всего это нужно будет сделать.
Если пользователь повторно регистрируется, то ему будет выдан ответ содержащий ошибку, без ключа auth_id. Согласен, из описание протокола это не очевидно. Там (в описании протокола) вообще не очевидно какие ещё поля есть в объекте JSON при возникновении ошибки.

**Comment by rus-ai** [comment]
А по 2 что все таки? Я смотрю там не только flow/from_flow дублируются но и user/from_user

**Comment by stepanskryabin** [comment]
по 2 пункту чуть позже отвечу

**Comment by stepanskryabin** [comment]
> 
> 
>     1. Нужен обязательно. Я его реализую.

Реализовано!

**Comment by stepanskryabin** [comment]
> 
> 
>     1. Да является. Нужно ли разделить регистрацию и аутентификацию вообще? Очень может быть! На текущем этапе считаю ненужным такое разделение, но в дальнейшем скорее всего это нужно будет сделать.
>        Если пользователь повторно регистрируется, то ему будет выдан ответ содержащий ошибку, без ключа auth_id. Согласен, из описание протокола это не очевидно. Там (в описании протокола) вообще не очевидно какие ещё поля есть в объекте JSON при возникновении ошибки.

Добавил в протокол дополнительный пример ответа на запрос в случае неуспеха (ошибки).

**Comment by stepanskryabin** [comment]
>     2. В методе send_message - есть два объекта указывающих на чат/канал. flow и from_flow. Зачем дублирование? Разве что рассматривать from_flow как пересланное сообщение. Но тогда нужен вариант from_user.
штош, пора и ответ держать!

Значит так:
а. метод send_message надо переделать хорошенько. так как при создании метода я не представлял каким образом сообщения конкретного пользователя будут храниться в БД, чтобы было понятно что это именно его сообщения.
б. тоже самое касается информации к какому потоку принадлежит сообщение конкретного пользователя.

так что надо будет переделать этот метод.
